quiz-keycloak:
  server-url: "http://192.168.100.8:8080"
  realm: "quiz-storage-realm"
  admin-client-id: "admin-client"
  admin-client-secret: "K1PqrzV8dxJiyycwsDMP1xXKrhlPJq8N"
  auth-client-id: "telegram-client"
  auth-client-secret: "PxAoadbc8KE93wBjQKPYQNmY9yTIJCI0"
  auth:
    telegram-id-parameter-name: "telegram_id"